In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

train test split

In [6]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

scaling

In [7]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [8]:
X_train

array([[-8.25273810e-02, -7.02789342e-01, -1.47973920e-01, ...,
        -8.74378488e-01, -8.56456635e-01, -6.82742226e-01],
       [-7.76068088e-01, -7.37660569e-02, -8.05494859e-01, ...,
        -7.76223499e-01,  6.29910810e-01, -7.47544338e-01],
       [-8.56518810e-01, -8.78486678e-02, -7.60051516e-01, ...,
         2.11183914e+00,  2.08671515e+00,  3.08394862e+00],
       ...,
       [ 6.45032488e-02,  1.82738641e+00,  2.02932833e-03, ...,
        -8.73316533e-01, -8.84377350e-01, -1.03615879e+00],
       [-3.21105384e-01,  7.07818846e-01, -4.09775835e-01, ...,
        -1.57680108e+00, -9.66497098e-01, -1.37432779e+00],
       [-6.81746552e-01, -4.72773365e-01, -7.04554336e-01, ...,
        -4.99979446e-02, -5.11553692e-01, -6.91455115e-01]])

In [9]:
X_test

array([[-1.44741549, -0.80840892, -1.34558698, ..., -1.13379894,
        -2.02255706, -0.35110789],
       [ 0.01456832,  2.02923717,  0.01409393, ..., -0.47038044,
        -1.63166706, -0.31081077],
       [-0.17407475, -1.13700318, -0.19060219, ...,  0.23672992,
         0.15361627, -0.60323711],
       ...,
       [ 1.75119425,  0.52943911,  1.62069708, ...,  0.47491127,
        -1.06011361, -0.67511845],
       [ 1.56255118,  0.55291013,  1.50809411, ...,  1.04381577,
         0.306359  , -0.06085977],
       [ 0.54720758, -1.01964809,  0.48662427, ..., -0.00448558,
        -0.17322033, -0.73774234]])

In [10]:
y_train

357    B
289    B
379    M
31     M
10     M
      ..
430    M
8      M
462    B
178    B
187    B
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [11]:
encoder = LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [12]:
y_train

array([0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0])

Numpy arrays to PyTorch tensors

In [13]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

Defining the Model

In [26]:
class MySimpleNN():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    # Clamp predictions to avoid log(0)
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    # Calculate loss
    loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

Important Parameters

In [27]:
learning_rate=0.1
epochs=25

Training Pipeline

In [33]:
# create model
model=MySimpleNN(X_train_tensor)
model.weights

tensor([[0.3695],
        [0.1889],
        [0.8563],
        [0.5775],
        [0.9857],
        [0.3563],
        [0.4304],
        [0.9323],
        [0.5140],
        [0.4601],
        [0.8561],
        [0.5199],
        [0.5455],
        [0.6027],
        [0.4282],
        [0.7137],
        [0.8173],
        [0.6538],
        [0.7877],
        [0.5679],
        [0.7745],
        [0.7982],
        [0.5099],
        [0.5005],
        [0.1359],
        [0.0564],
        [0.5795],
        [0.6174],
        [0.4952],
        [0.9438]], dtype=torch.float64, requires_grad=True)

In [34]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [35]:
# define loop
for epoch in range(epochs):
  # forward pass
  y_pred=model.forward(X_train_tensor)
  # print(y_pred)

  # loss calculate
  loss=model.loss_function(y_pred,y_train_tensor)
  # print(f'Epoch: {epoch}, Loss: {loss.item()}')

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 4.044313631951052
Epoch: 2, Loss: 3.9423877671923626
Epoch: 3, Loss: 3.8355687338155544
Epoch: 4, Loss: 3.72622300592906
Epoch: 5, Loss: 3.6129125563455617
Epoch: 6, Loss: 3.4938869013720484
Epoch: 7, Loss: 3.3704324830317924
Epoch: 8, Loss: 3.2413355897086884
Epoch: 9, Loss: 3.107471579637458
Epoch: 10, Loss: 2.970630209623855
Epoch: 11, Loss: 2.828149457241011
Epoch: 12, Loss: 2.679801591976017
Epoch: 13, Loss: 2.5258535955907853
Epoch: 14, Loss: 2.370032210730969
Epoch: 15, Loss: 2.217041793704075
Epoch: 16, Loss: 2.066800194314119
Epoch: 17, Loss: 1.919188521763085
Epoch: 18, Loss: 1.7759294858839398
Epoch: 19, Loss: 1.6401671435832716
Epoch: 20, Loss: 1.5036410063748358
Epoch: 21, Loss: 1.3757132381496486
Epoch: 22, Loss: 1.259818104700722
Epoch: 23, Loss: 1.1593913476058721
Epoch: 24, Loss: 1.074740998151573
Epoch: 25, Loss: 1.0054438434576616

In [36]:
model.weights

tensor([[-0.1320],
        [-0.1797],
        [ 0.3316],
        [ 0.0845],
        [ 0.4946],
        [-0.3252],
        [-0.2588],
        [ 0.2357],
        [ 0.0538],
        [ 0.1522],
        [ 0.3493],
        [ 0.3135],
        [ 0.0460],
        [ 0.1799],
        [ 0.1845],
        [ 0.1606],
        [ 0.3622],
        [ 0.0476],
        [ 0.5686],
        [ 0.1368],
        [ 0.2318],
        [ 0.4274],
        [-0.0493],
        [-0.0206],
        [-0.3089],
        [-0.5344],
        [-0.0533],
        [-0.0622],
        [ 0.1310],
        [ 0.4824]], dtype=torch.float64, requires_grad=True)

In [37]:
model.bias

tensor([-0.0856], dtype=torch.float64, requires_grad=True)

Evaluation

In [40]:
# model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.5).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

# print(y_pred)

Accuracy: 0.5220067501068115