In [105]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [106]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [107]:
df.shape

(569, 33)

In [108]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [109]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

train test split

In [110]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

scaling

In [111]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [112]:
X_train

array([[-0.49127087, -0.30610878, -0.52258754, ..., -0.26585525,
         0.88779275, -0.80884856],
       [-0.47713593, -1.57929763, -0.50451517, ..., -0.28728797,
        -0.11372288, -0.87592543],
       [-0.70894895, -0.18408525, -0.73329492, ..., -0.72004655,
        -0.25246788, -1.02832408],
       ...,
       [ 0.63387036,  0.0599618 ,  0.76671165, ...,  0.98332282,
         0.66930924,  0.39316893],
       [-0.80789353, -1.42043681, -0.83228221, ..., -0.87782786,
        -0.06269024, -0.87538882],
       [-0.75418075, -0.14724796, -0.75465317, ..., -0.41634032,
         0.25785855, -0.86948605]])

In [113]:
X_test

array([[ 0.11087758,  1.78210513,  0.0458706 , ..., -0.86916357,
        -0.88240207, -1.04066622],
       [-0.55346461,  0.79900994, -0.50862252, ..., -0.05487214,
        -1.12799667,  0.50746791],
       [ 1.86078315,  0.458265  ,  1.91677145, ...,  1.49710012,
        -0.66710811,  0.31965268],
       ...,
       [-1.20225835,  2.06068714, -1.20974827, ..., -0.97511114,
        -0.92067656, -0.63981485],
       [ 0.481213  , -1.22473871,  0.44633785, ...,  0.37378229,
        -0.27957897, -0.71494095],
       [-1.29243927, -0.21401555, -1.2861451 , ..., -0.94683818,
        -0.70857213, -0.14344602]])

In [114]:
y_train

409    B
170    B
251    B
27     M
456    B
      ..
452    B
82     M
479    M
153    B
515    B
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [115]:
encoder = LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [116]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0])

Numpy arrays to PyTorch tensors

In [117]:
X_train_tensor=torch.from_numpy(X_train).float()
X_test_tensor=torch.from_numpy(X_test).float()
y_train_tensor=torch.from_numpy(y_train).float()
y_test_tensor=torch.from_numpy(y_test).float()

In [118]:
X_train_tensor.shape

torch.Size([455, 30])

In [119]:
y_train_tensor.shape

torch.Size([455])

Defining the Model

In [120]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

Important Parameters

In [121]:
learning_rate=0.1
epochs=25

In [122]:
#define loss function
loss_function=nn.BCELoss()

Training Pipeline

In [123]:
# create model
model=MySimpleNN(X_train_tensor.shape[1])
model.float()
model.linear.weight

Parameter containing:
tensor([[-0.0004,  0.0448,  0.0995, -0.1499,  0.1357,  0.0260,  0.1056, -0.0108,
          0.1339,  0.0572, -0.0653, -0.1480, -0.0150, -0.0507,  0.0641, -0.1382,
          0.1488, -0.0992, -0.0530,  0.0679, -0.1307,  0.0477,  0.0844, -0.1588,
         -0.0687,  0.0303,  0.1215,  0.0392,  0.0322, -0.0746]],
       requires_grad=True)

In [124]:
# define optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

In [125]:
model.linear.bias

Parameter containing:
tensor([0.1268], requires_grad=True)

In [126]:
# define loop
for epoch in range(epochs):
  # forward pass
  y_pred=model(X_train_tensor)
  # print(y_pred)

  # loss calculate
  loss=loss_function(y_pred,y_train_tensor.view(-1,1))
  # print(f'Epoch: {epoch}, Loss: {loss.item()}')

  #clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # zero gradients
  optimizer.zero_grad()

  # print loss
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7333755493164062
Epoch: 2, Loss: 0.5586166977882385
Epoch: 3, Loss: 0.4648023545742035
Epoch: 4, Loss: 0.4068158268928528
Epoch: 5, Loss: 0.36667346954345703
Epoch: 6, Loss: 0.33677464723587036
Epoch: 7, Loss: 0.31338050961494446
Epoch: 8, Loss: 0.2944187819957733
Epoch: 9, Loss: 0.2786376178264618
Epoch: 10, Loss: 0.26523083448410034
Epoch: 11, Loss: 0.25365275144577026
Epoch: 12, Loss: 0.24351926147937775
Epoch: 13, Loss: 0.23455114662647247
Epoch: 14, Loss: 0.22654002904891968
Epoch: 15, Loss: 0.21932680904865265
Epoch: 16, Loss: 0.21278753876686096
Epoch: 17, Loss: 0.2068241685628891
Epoch: 18, Loss: 0.20135784149169922
Epoch: 19, Loss: 0.19632437825202942
Epoch: 20, Loss: 0.19167084991931915
Epoch: 21, Loss: 0.1873532086610794
Epoch: 22, Loss: 0.1833343803882599
Epoch: 23, Loss: 0.1795828640460968
Epoch: 24, Loss: 0.17607177793979645
Epoch: 25, Loss: 0.17277784645557404

In [127]:
model.linear.weight

Parameter containing:
tensor([[ 0.2673,  0.2195,  0.3666,  0.1144,  0.1935,  0.1573,  0.2844,  0.2351,
          0.1716, -0.0393,  0.1454, -0.1361,  0.1817,  0.1620,  0.0329, -0.1413,
          0.0980, -0.0532, -0.0805, -0.0137,  0.1621,  0.2535,  0.3720,  0.1211,
          0.0507,  0.1723,  0.2741,  0.2811,  0.1478, -0.0333]],
       requires_grad=True)

Evaluation

In [128]:
# model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.5).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

# print(y_pred)

Accuracy: 0.5083102583885193