In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

train test split

In [6]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

scaling

In [7]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [8]:
X_train

array([[ 0.26063395, -0.88789728,  0.23733928, ...,  0.36574167,
         0.08533153, -0.01792739],
       [-0.56628579, -0.07879376, -0.60951001, ..., -0.95648373,
        -0.02986484, -0.1780141 ],
       [ 0.36470208,  0.84248635,  0.34935639, ...,  0.51321305,
        -0.53423813, -0.89811741],
       ...,
       [-0.32721035, -0.69218492, -0.37040441, ..., -0.47879807,
         0.19430107, -0.82868913],
       [-0.62816413, -0.12652848, -0.55777847, ...,  0.6196357 ,
         2.89830235,  3.22856227],
       [ 0.27188456, -0.59432875,  0.28947815, ..., -0.18309514,
        -1.12423035,  0.08937087]])

In [9]:
X_test

array([[-0.14438796, -1.27216178, -0.12355945, ..., -0.34881041,
         0.25812609, -0.12407808],
       [ 0.61221547,  0.06679714,  0.74039791, ...,  0.96778979,
         0.65197313,  0.42618413],
       [-0.88130283, -0.15278258, -0.864909  , ..., -0.53170533,
        -1.00903398, -0.37941352],
       ...,
       [ 0.20438091, -0.37474903,  0.1733877 , ..., -0.46769971,
         1.09096471, -0.63589653],
       [-0.96286974,  1.42962341, -0.96185471, ..., -0.79791399,
         0.79363354, -0.1412917 ],
       [ 1.7035245 ,  2.15280443,  1.61209463, ...,  0.74430223,
        -0.50933081, -1.00771083]])

In [10]:
y_train

227    B
346    B
91     M
191    B
373    M
      ..
138    M
53     M
195    B
31     M
500    B
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [11]:
encoder = LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [12]:
y_train

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0])

Numpy arrays to PyTorch tensors

In [13]:
X_train_tensor=torch.from_numpy(X_train).float()
X_test_tensor=torch.from_numpy(X_test).float()
y_train_tensor=torch.from_numpy(y_train).float()
y_test_tensor=torch.from_numpy(y_test).float()

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

In [17]:
from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features=features
    self.labels=labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]

In [18]:
train_dataset=CustomDataset(X_train_tensor,y_train_tensor)
test_dataset=CustomDataset(X_test_tensor,y_test_tensor)

In [19]:
train_dataset[10]

(tensor([-1.2084, -0.5347, -1.1863, -1.0061,  0.5035, -0.3840, -0.5625, -0.7882,
         -0.8387,  1.0898, -0.0152,  0.3830, -0.0663, -0.3674,  2.2045,  0.1965,
         -0.1576, -0.2526,  1.4591,  0.3332, -1.0562, -0.6798, -1.0323, -0.8766,
          0.6217, -0.4963, -0.6753, -0.9198, -0.5700,  0.0429]),
 tensor(0.))

In [20]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

Defining the Model

In [21]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

Important Parameters

In [22]:
learning_rate=0.1
epochs=25

In [23]:
# create model
model=MySimpleNN(X_train_tensor.shape[1])
model.float()

# define optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

#define loss function
loss_function=nn.BCELoss()

Training Pipeline

In [24]:
# define loop
for epoch in range(epochs):

  for batch_features,batch_labels in train_loader:

    # forward pass
    y_pred=model(batch_features)

    # loss calculate
    loss=loss_function(y_pred,batch_labels.view(-1,1))

    #clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

    # print loss
    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6198804378509521
Epoch: 1, Loss: 0.4969080984592438
Epoch: 1, Loss: 0.38201019167900085
Epoch: 1, Loss: 0.3709571957588196
Epoch: 1, Loss: 0.28721854090690613
Epoch: 1, Loss: 0.3422558307647705
Epoch: 1, Loss: 0.3489885628223419
Epoch: 1, Loss: 0.3043878674507141
Epoch: 1, Loss: 0.3398083448410034
Epoch: 1, Loss: 0.28724172711372375
Epoch: 1, Loss: 0.2400166392326355
Epoch: 1, Loss: 0.25901055335998535
Epoch: 1, Loss: 0.25638824701309204
Epoch: 1, Loss: 0.2036258727312088
Epoch: 1, Loss: 0.18340015411376953
Epoch: 2, Loss: 0.23272021114826202
Epoch: 2, Loss: 0.18573755025863647
Epoch: 2, Loss: 0.21416522562503815
Epoch: 2, Loss: 0.17699453234672546
Epoch: 2, Loss: 0.21102875471115112
Epoch: 2, Loss: 0.1304021030664444
Epoch: 2, Loss: 0.15336669981479645
Epoch: 2, Loss: 0.2074975222349167
Epoch: 2, Loss: 0.18597812950611115
Epoch: 2, Loss: 0.13576897978782654
Epoch: 2, Loss: 0.17991292476654053
Epoch: 2, Loss: 0.1918739527463913
Epoch: 2, Loss: 0.1991063952445984
Epoch: 2, Loss: 0.18212667107582092
Epoch: 2, Loss: 0.2138480842113495
Epoch: 3, Loss: 0.1508651226758957
Epoch: 3, Loss: 0.21409769356250763
Epoch: 3, Loss: 0.15528935194015503
Epoch: 3, Loss: 0.13366350531578064
Epoch: 3, Loss: 0.13843947649002075
Epoch: 3, Loss: 0.12094102799892426
Epoch: 3, Loss: 0.1594206988811493
Epoch: 3, Loss: 0.15175259113311768
Epoch: 3, Loss: 0.1273830235004425
Epoch: 3, Loss: 0.08547443151473999
Epoch: 3, Loss: 0.10909220576286316
Epoch: 3, Loss: 0.14495231211185455
Epoch: 3, Loss: 0.2309192419052124
Epoch: 3, Loss: 0.1781672090291977
Epoch: 3, Loss: 0.0892246812582016
Epoch: 4, Loss: 0.1025831550359726
Epoch: 4, Loss: 0.13886623084545135
Epoch: 4, Loss: 0.15254586935043335
Epoch: 4, Loss: 0.07940284162759781
Epoch: 4, Loss: 0.08882109075784683
Epoch: 4, Loss: 0.18306414783000946
Epoch: 4, Loss: 0.10306297242641449
Epoch: 4, Loss: 0.15949565172195435
Epoch: 4, Loss: 0.12795814871788025
Epoch: 4, Loss: 0.1961442232131958
Epoch: 4, Loss: 0.07862096279859543
Epoch: 4, Loss: 0.12007937580347061
Epoch: 4, Loss: 0.18098996579647064
Epoch: 4, Loss: 0.09124408662319183
Epoch: 4, Loss: 0.17145517468452454
Epoch: 5, Loss: 0.10548284649848938
Epoch: 5, Loss: 0.11606656014919281
Epoch: 5, Loss: 0.1741069257259369
Epoch: 5, Loss: 0.09962451457977295
Epoch: 5, Loss: 0.08697929978370667
Epoch: 5, Loss: 0.19583749771118164
Epoch: 5, Loss: 0.09972049295902252
Epoch: 5, Loss: 0.07148206979036331
Epoch: 5, Loss: 0.13090065121650696
Epoch: 5, Loss: 0.13171906769275665
Epoch: 5, Loss: 0.0839785635471344
Epoch: 5, Loss: 0.11417604982852936
Epoch: 5, Loss: 0.1326827108860016
Epoch: 5, Loss: 0.1051645576953888
Epoch: 5, Loss: 0.06232915446162224
Epoch: 6, Loss: 0.08928290009498596
Epoch: 6, Loss: 0.06953448057174683
Epoch: 6, Loss: 0.16603505611419678
Epoch: 6, Loss: 0.09755939245223999
Epoch: 6, Loss: 0.13031300902366638
Epoch: 6, Loss: 0.09665029495954514
Epoch: 6, Loss: 0.14349263906478882
Epoch: 6, Loss: 0.09986906498670578
Epoch: 6, Loss: 0.10090146958827972
Epoch: 6, Loss: 0.06988631933927536
Epoch: 6, Loss: 0.12767896056175232
Epoch: 6, Loss: 0.05972982943058014
Epoch: 6, Loss: 0.13398312032222748
Epoch: 6, Loss: 0.11248581856489182
Epoch: 6, Loss: 0.19051682949066162
Epoch: 7, Loss: 0.15944842994213104
Epoch: 7, Loss: 0.053058065474033356
Epoch: 7, Loss: 0.0736159086227417
Epoch: 7, Loss: 0.09884271025657654
Epoch: 7, Loss: 0.0735461637377739
Epoch: 7, Loss: 0.11028969287872314
Epoch: 7, Loss: 0.11303409188985825
Epoch: 7, Loss: 0.1327168345451355
Epoch: 7, Loss: 0.1009734645485878
Epoch: 7, Loss: 0.05904499068856239
Epoch: 7, Loss: 0.08566455543041229
Epoch: 7, Loss: 0.10240790247917175
Epoch: 7, Loss: 0.15096841752529144
Epoch: 7, Loss: 0.11809780448675156
Epoch: 7, Loss: 0.08904172480106354
Epoch: 8, Loss: 0.07092063128948212
Epoch: 8, Loss: 0.10745005309581757
Epoch: 8, Loss: 0.09569760411977768
Epoch: 8, Loss: 0.07171332836151123
Epoch: 8, Loss: 0.09826681017875671
Epoch: 8, Loss: 0.08239691704511642
Epoch: 8, Loss: 0.08468732982873917
Epoch: 8, Loss: 0.04697657376527786
Epoch: 8, Loss: 0.11493418365716934
Epoch: 8, Loss: 0.09880747646093369
Epoch: 8, Loss: 0.11752404272556305
Epoch: 8, Loss: 0.09601395577192307
Epoch: 8, Loss: 0.12926656007766724
Epoch: 8, Loss: 0.16332539916038513
Epoch: 8, Loss: 0.02036171779036522
Epoch: 9, Loss: 0.09813296049833298
Epoch: 9, Loss: 0.182399719953537
Epoch: 9, Loss: 0.09947683662176132
Epoch: 9, Loss: 0.053501196205616
Epoch: 9, Loss: 0.05863190442323685
Epoch: 9, Loss: 0.10112833976745605
Epoch: 9, Loss: 0.10944908112287521
Epoch: 9, Loss: 0.04763328656554222
Epoch: 9, Loss: 0.07030398398637772
Epoch: 9, Loss: 0.09340709447860718
Epoch: 9, Loss: 0.09620358049869537
Epoch: 9, Loss: 0.08350953459739685
Epoch: 9, Loss: 0.14279145002365112
Epoch: 9, Loss: 0.07210654765367508
Epoch: 9, Loss: 0.09127022325992584
Epoch: 10, Loss: 0.061863020062446594
Epoch: 10, Loss: 0.08978236466646194
Epoch: 10, Loss: 0.1710352599620819
Epoch: 10, Loss: 0.05676311254501343
Epoch: 10, Loss: 0.06852036714553833
Epoch: 10, Loss: 0.07715239375829697
Epoch: 10, Loss: 0.0488886758685112
Epoch: 10, Loss: 0.05799420550465584
Epoch: 10, Loss: 0.07655403017997742
Epoch: 10, Loss: 0.0701989158987999
Epoch: 10, Loss: 0.07701980322599411
Epoch: 10, Loss: 0.09596569091081619
Epoch: 10, Loss: 0.12577588856220245
Epoch: 10, Loss: 0.13246244192123413
Epoch: 10, Loss: 0.32832029461860657
Epoch: 11, Loss: 0.04611921310424805
Epoch: 11, Loss: 0.059200599789619446
Epoch: 11, Loss: 0.08725262433290482
Epoch: 11, Loss: 0.11787588149309158
Epoch: 11, Loss: 0.05868024006485939
Epoch: 11, Loss: 0.09921272099018097
Epoch: 11, Loss: 0.19104330241680145
Epoch: 11, Loss: 0.043639931827783585
Epoch: 11, Loss: 0.09076844155788422
Epoch: 11, Loss: 0.13915976881980896
Epoch: 11, Loss: 0.05263635143637657
Epoch: 11, Loss: 0.14498920738697052
Epoch: 11, Loss: 0.053344808518886566
Epoch: 11, Loss: 0.05138033255934715
Epoch: 11, Loss: 0.05292551591992378
Epoch: 12, Loss: 0.04665669426321983
Epoch: 12, Loss: 0.06943916529417038
Epoch: 12, Loss: 0.046127185225486755
Epoch: 12, Loss: 0.07464466243982315
Epoch: 12, Loss: 0.03008965589106083
Epoch: 12, Loss: 0.046642329543828964
Epoch: 12, Loss: 0.1194593757390976
Epoch: 12, Loss: 0.04579237848520279
Epoch: 12, Loss: 0.08445478975772858
Epoch: 12, Loss: 0.09727535396814346
Epoch: 12, Loss: 0.05466518923640251
Epoch: 12, Loss: 0.05117359384894371
Epoch: 12, Loss: 0.3365432620048523
Epoch: 12, Loss: 0.09750115126371384
Epoch: 12, Loss: 0.054898884147405624
Epoch: 13, Loss: 0.04045679047703743
Epoch: 13, Loss: 0.06858539581298828
Epoch: 13, Loss: 0.08227046579122543
Epoch: 13, Loss: 0.11765146255493164
Epoch: 13, Loss: 0.1407008022069931
Epoch: 13, Loss: 0.046492427587509155
Epoch: 13, Loss: 0.03696218878030777
Epoch: 13, Loss: 0.057415738701820374
Epoch: 13, Loss: 0.06525493413209915
Epoch: 13, Loss: 0.1937127411365509
Epoch: 13, Loss: 0.09455407410860062
Epoch: 13, Loss: 0.08193017542362213
Epoch: 13, Loss: 0.07320839911699295
Epoch: 13, Loss: 0.06592930853366852
Epoch: 13, Loss: 0.0716332420706749
Epoch: 14, Loss: 0.10718560963869095
Epoch: 14, Loss: 0.09998916834592819
Epoch: 14, Loss: 0.03167267143726349
Epoch: 14, Loss: 0.045621179044246674
Epoch: 14, Loss: 0.0657990574836731
Epoch: 14, Loss: 0.06004370376467705
Epoch: 14, Loss: 0.0841575637459755
Epoch: 14, Loss: 0.1433245986700058
Epoch: 14, Loss: 0.06893648952245712
Epoch: 14, Loss: 0.0798875242471695
Epoch: 14, Loss: 0.060023173689842224
Epoch: 14, Loss: 0.03533210977911949
Epoch: 14, Loss: 0.10087032616138458
Epoch: 14, Loss: 0.1561792641878128
Epoch: 14, Loss: 0.0872461125254631
Epoch: 15, Loss: 0.03684787452220917
Epoch: 15, Loss: 0.08751392364501953
Epoch: 15, Loss: 0.08323968201875687
Epoch: 15, Loss: 0.08722776174545288
Epoch: 15, Loss: 0.056020524352788925
Epoch: 15, Loss: 0.06856389343738556
Epoch: 15, Loss: 0.06740915030241013
Epoch: 15, Loss: 0.04425005614757538
Epoch: 15, Loss: 0.14529754221439362
Epoch: 15, Loss: 0.09910466521978378
Epoch: 15, Loss: 0.05849717557430267
Epoch: 15, Loss: 0.07518724352121353
Epoch: 15, Loss: 0.058177147060632706
Epoch: 15, Loss: 0.15739865601062775
Epoch: 15, Loss: 0.04008925333619118
Epoch: 16, Loss: 0.07065248489379883
Epoch: 16, Loss: 0.04111884534358978
Epoch: 16, Loss: 0.038846127688884735
Epoch: 16, Loss: 0.039180688560009
Epoch: 16, Loss: 0.16969236731529236
Epoch: 16, Loss: 0.05374172329902649
Epoch: 16, Loss: 0.04488804191350937
Epoch: 16, Loss: 0.13216955959796906
Epoch: 16, Loss: 0.11941451579332352
Epoch: 16, Loss: 0.02325192093849182
Epoch: 16, Loss: 0.21168407797813416
Epoch: 16, Loss: 0.06580297648906708
Epoch: 16, Loss: 0.035719260573387146
Epoch: 16, Loss: 0.06550031900405884
Epoch: 16, Loss: 0.007527858950197697
Epoch: 17, Loss: 0.018445134162902832
Epoch: 17, Loss: 0.0853867307305336
Epoch: 17, Loss: 0.04018804430961609
Epoch: 17, Loss: 0.041622914373874664
Epoch: 17, Loss: 0.032888125628232956
Epoch: 17, Loss: 0.09177780151367188
Epoch: 17, Loss: 0.09018265455961227
Epoch: 17, Loss: 0.14589612185955048
Epoch: 17, Loss: 0.04565249755978584
Epoch: 17, Loss: 0.1031462699174881
Epoch: 17, Loss: 0.046936389058828354
Epoch: 17, Loss: 0.09793108701705933
Epoch: 17, Loss: 0.17476384341716766
Epoch: 17, Loss: 0.075880266726017
Epoch: 17, Loss: 0.027089798822999
Epoch: 18, Loss: 0.04198715463280678
Epoch: 18, Loss: 0.12288224697113037
Epoch: 18, Loss: 0.0404016487300396
Epoch: 18, Loss: 0.18933789432048798
Epoch: 18, Loss: 0.0490499883890152
Epoch: 18, Loss: 0.023712459951639175
Epoch: 18, Loss: 0.08132636547088623
Epoch: 18, Loss: 0.05655931681394577
Epoch: 18, Loss: 0.15677222609519958
Epoch: 18, Loss: 0.03399781137704849
Epoch: 18, Loss: 0.06386787444353104
Epoch: 18, Loss: 0.04165928438305855
Epoch: 18, Loss: 0.07775597274303436
Epoch: 18, Loss: 0.08259530365467072
Epoch: 18, Loss: 0.08874768763780594
Epoch: 19, Loss: 0.05166573077440262
Epoch: 19, Loss: 0.06420648097991943
Epoch: 19, Loss: 0.06995194405317307
Epoch: 19, Loss: 0.042626794427633286
Epoch: 19, Loss: 0.08721159398555756
Epoch: 19, Loss: 0.16071239113807678
Epoch: 19, Loss: 0.16038228571414948
Epoch: 19, Loss: 0.032509803771972656
Epoch: 19, Loss: 0.016168352216482162
Epoch: 19, Loss: 0.11551900953054428
Epoch: 19, Loss: 0.07573945820331573
Epoch: 19, Loss: 0.04762498661875725
Epoch: 19, Loss: 0.05443601310253143
Epoch: 19, Loss: 0.06007438153028488
Epoch: 19, Loss: 0.11190688610076904
Epoch: 20, Loss: 0.04534592851996422
Epoch: 20, Loss: 0.09095719456672668
Epoch: 20, Loss: 0.08465120941400528
Epoch: 20, Loss: 0.04818970337510109
Epoch: 20, Loss: 0.10025762021541595
Epoch: 20, Loss: 0.08354194462299347
Epoch: 20, Loss: 0.04330521076917648
Epoch: 20, Loss: 0.063056580722332
Epoch: 20, Loss: 0.02096020057797432
Epoch: 20, Loss: 0.07798249274492264
Epoch: 20, Loss: 0.04518558830022812
Epoch: 20, Loss: 0.2162427455186844
Epoch: 20, Loss: 0.053159911185503006
Epoch: 20, Loss: 0.0737476795911789
Epoch: 20, Loss: 0.01670612394809723
Epoch: 21, Loss: 0.03396839275956154
Epoch: 21, Loss: 0.2503170371055603
Epoch: 21, Loss: 0.0871262475848198
Epoch: 21, Loss: 0.051329806447029114
Epoch: 21, Loss: 0.10030367225408554
Epoch: 21, Loss: 0.05174599960446358
Epoch: 21, Loss: 0.10010264813899994
Epoch: 21, Loss: 0.0460604690015316
Epoch: 21, Loss: 0.0734332874417305
Epoch: 21, Loss: 0.05141263082623482
Epoch: 21, Loss: 0.027543699368834496
Epoch: 21, Loss: 0.0611148402094841
Epoch: 21, Loss: 0.07692740112543106
Epoch: 21, Loss: 0.024265175685286522
Epoch: 21, Loss: 0.011799907311797142
Epoch: 22, Loss: 0.07434132695198059
Epoch: 22, Loss: 0.05581444874405861
Epoch: 22, Loss: 0.05406080558896065
Epoch: 22, Loss: 0.03642411530017853
Epoch: 22, Loss: 0.06946167349815369
Epoch: 22, Loss: 0.05389250069856644
Epoch: 22, Loss: 0.07881561666727066
Epoch: 22, Loss: 0.06572289764881134
Epoch: 22, Loss: 0.08589830994606018
Epoch: 22, Loss: 0.11428503692150116
Epoch: 22, Loss: 0.15564307570457458
Epoch: 22, Loss: 0.029173772782087326
Epoch: 22, Loss: 0.03956306725740433
Epoch: 22, Loss: 0.04522549733519554
Epoch: 22, Loss: 0.30968669056892395
Epoch: 23, Loss: 0.05603361874818802
Epoch: 23, Loss: 0.06891091912984848
Epoch: 23, Loss: 0.04848587140440941
Epoch: 23, Loss: 0.024718191474676132
Epoch: 23, Loss: 0.06737739592790604
Epoch: 23, Loss: 0.16014820337295532
Epoch: 23, Loss: 0.07315785437822342
Epoch: 23, Loss: 0.028053373098373413
Epoch: 23, Loss: 0.1074015349149704
Epoch: 23, Loss: 0.15563781559467316
Epoch: 23, Loss: 0.045574598014354706
Epoch: 23, Loss: 0.09425066411495209
Epoch: 23, Loss: 0.04059740900993347
Epoch: 23, Loss: 0.04082261770963669
Epoch: 23, Loss: 0.03254967927932739
Epoch: 24, Loss: 0.045877452939748764
Epoch: 24, Loss: 0.013018470257520676
Epoch: 24, Loss: 0.027584122493863106
Epoch: 24, Loss: 0.0853390097618103
Epoch: 24, Loss: 0.13147211074829102
Epoch: 24, Loss: 0.04919012635946274
Epoch: 24, Loss: 0.047100309282541275
Epoch: 24, Loss: 0.29979294538497925
Epoch: 24, Loss: 0.03596721589565277
Epoch: 24, Loss: 0.09044899046421051
Epoch: 24, Loss: 0.05480576306581497
Epoch: 24, Loss: 0.04538550227880478
Epoch: 24, Loss: 0.024048173800110817
Epoch: 24, Loss: 0.05735263228416443
Epoch: 24, Loss: 0.015877267345786095
Epoch: 25, Loss: 0.054605234414339066
Epoch: 25, Loss: 0.1427602767944336
Epoch: 25, Loss: 0.049172982573509216
Epoch: 25, Loss: 0.010392922908067703
Epoch: 25, Loss: 0.032036494463682175
Epoch: 25, Loss: 0.07548954337835312
Epoch: 25, Loss: 0.16111133992671967
Epoch: 25, Loss: 0.09129029512405396
Epoch: 25, Loss: 0.0492822639644146
Epoch: 25, Loss: 0.059566374868154526
Epoch: 25, Loss: 0.04827497899532318
Epoch: 25, Loss: 0.08281666785478592
Epoch: 25, Loss: 0.08530670404434204
Epoch: 25, Loss: 0.05314873903989792
Epoch: 25, Loss: 0.017603838816285133

Evaluation

In [28]:
# Model evaluation using test_loader
model.eval() # set the model to evaluation mode
accuracy_list=[]

with torch.no_grad():
  for batch_features,batch_labels in test_loader:
    # Forward pass
    y_pred=model(batch_features)
    y_pred=(y_pred>0.5).float()  # Convert probabilities to binary prediction

    # Calculate accuracy for the current batch

    # batch_accuracy=(y_pred==batch_labels.view(-1,1)).float().mean().item()
    batch_accuracy=(y_pred.view(-1)==batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

  # Calculate overall accuracy
  overall_accuracy=sum(accuracy_list)/len(accuracy_list)
  print(f'Overall Accuracy: {overall_accuracy}')

Overall Accuracy: 0.9921875